version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./gestorUsuariosBack.war:/usr/share/nginx/html/gestorUsuariosBack.war:ro
