spring:
  mail:
    default-encoding: UTF-8
    host: mail.jaimetorres.net
#    username: gestorclientes@jaimetorres.net  
#    password: G3st0r3*
    username: jaimev_tec@jaimetorres.net 
    password: Master12*
    port: 25
    properties:
      mail:
        ssl:
          enable: true
        smtp:
          auth: true
          starttls:
            enable: true       
            required: true     
    protocol: smtp
    test-connection: false
    
#server:
  #ssl:
    #key-store: classpath:helpvoz.p12
    #key-store-password: master
    #key-alias: gestorCli 
    #key-store-type: PKCS12 
  #port: 8443
  
  
  
  
  
